name: Deploy all Slidev projects

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Setup @antfu/ni
        run: npm i -g @antfu/ni

      - name: Install dependencies and build lab-full-stack
        working-directory: lab-full-stack
        run: |
          nci
          nr build --base /${{ github.event.repository.name }}/lab-full-stack/
          mv dist ../_site/lab-full-stack

    #   - name: Install dependencies and build lab-other
    #     working-directory: lab-other
    #     run: |
    #       nci
    #       nr build --base /${{ github.event.repository.name }}/lab-other/
    #       mv dist ../_site/lab-other

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4